# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binfo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='name',
            new_name='name_ru',
        ),
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(db_index=True, default='', max_length=200, verbose_name='City'),
        ),
    ]
