# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binfo', '0003_auto_20161030_0941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-favorite', 'name_ru'], 'verbose_name': 'Город', 'verbose_name_plural': 'Города'},
        ),
    ]
