# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('binfo', '0004_auto_20161030_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-favorite', 'iso'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
