# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('binfo', '0005_auto_20161030_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='worktime',
            field=models.TextField(default='', max_length=500, verbose_name='Рабочее время'),
        ),
    ]
